### ISSUE TITLE
Websites url's redirect to localhost

### ISSUE THREAD

**Issue by Metallist1** [organizationGB/DevOps#23]
When trying to click buttons in http://206.189.48.173:8080 , all buttons redirect to localhost:8080.

**Comment by oliverjarvis** [comment]
Dear Mettalist1,

I hope this message finds you well. I just wanted to give you a quick update regarding the open issue on GitHub. I'm happy to inform you that we've managed to resolve the issue.

I apologize for any inconvenience this may have caused you and appreciate your patience while we worked to find a solution.

If you have any further questions or concerns, please do not hesitate to reach out to us.

Best regards,
Oliver
