### ISSUE TITLE
White Hat Attack (Group i) Security Report

### ISSUE THREAD

**Issue by Metallist1** [organizationGB/DevOps#38]
Hello, 
As part of the assignment we completed a full security assessment of your website.

Security Report: https://drive.google.com/file/d/1wX81jybYIlePjJ1gCtV4mosg1aER5iTS/view?usp=sharing
Owasp zap report: https://drive.google.com/file/d/1_iZZS9E-xUKJj75-CZBRqS_Ubx1o4hoP/view?usp=share_link (This is a PDF version of the report. It might not be an optimal viewing experience. You can find the full generated website here( https://drive.google.com/drive/folders/1DtbbeUOQbFgdGoZgFy7CHlGZyEyPUIHH?usp=share_link )

The short version:
1. Change your PostgreSQL super user password as we managed to get inside your database using default credentials. 
2. Change your websites session secret to be taken from Github secrets. 

Extra tips:
Seems your website is running very slowly due to amount of data inside the database. Consider implementing indexing on most critical SQL calls (https://www.tutorialspoint.com/postgresql/postgresql_indexes.htm). It is very simple and it helped us decrease our websites load time from 5 seconds to 0.3 seconds !

**Comment by bjarkedc** [comment]
Cool report, one thing that is not clear to me - the DB you got access to, was that an azure hosted one?

**Comment by Metallist1** [comment]
It does seems so.

To elaborate more :
You seemed to have a old deployment of PostgreSQL on 206.189.48.173 with port: 5432
We used pgAdmin to connect to it .
After connecting we noticed 2 databases running. "Minitwit-db" which was not used and "Postgres" which had direct connection to your azure database. 
So while we technically had no direct connection to your azure database, we could execute SQL commands from pgAdmin that would be executed inside Azure deployed database. Additionally, we could view commands being executed in the database. So even if we had no control, we could spy on users as a man in the middle. 

Lastly, since we are executing commands from your own website. This allows us to completely bypass the Azure firewall 
restrictions. 
So I think if you just closed down the old database container it should resolve this issue as there would be no way for us to connect and execute commands. Or if that is not an option, just change the super user password and you should be fine.

**Comment by bjarkedc** [comment]
Im kinda confused, you say "executing commands from your own website" are you only talking about the azure database which you connect to via PGAdmin? Or do you mean from inside the container on the server (so you have command line access on our server)? 

Another question - Did you find this via the tool provided in the pen-test lecture or was this found searching our repository "manually"?

**Comment by Metallist1** [comment]
Ah I see there can be a bit of confusion and I worded it wrongly. 

-I am referring only to the azure database which I connect to with PGAdmin. Sending sql commands from the "db" container is identical to sending sql commands from your website. 
-We dont have command line access to your server. But I assume with some XSS injections we could compromise your SSH key. 

For the second question. Its a combination of both utilizing Metasploit to gather information on the server and searching your repository manually.

**Comment by bjarkedc** [comment]
Thanks for the clarification. We knew about the obvious problems, but actually thought you would not look through our repository (We thought that was the part of the assignment we were supposed to do on our own, since normally this kind of repository are private).  We interpret the task differently - i.e. that we were only supposed to use the pen-test frameworks and not go through the repository.  So we appreciate the thorough report!  :v:
